---
admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  clusters:
    name: "my-service"
    type: "STRICT_DNS"
    connect_timeout: "1s"
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: "my-service"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8000

  listeners:
    access_log:
      path: "/dev/stdout"
      config: {}
    address:
      socket_address:
        address: "127.0.0.1"
        port_value: 9000
    filter_chains:
      filters:
        name: "envoy.http_connection_manager"
        config:
          stat_prefix: "ingress_http"
          http_filters:
            - name: "envoy.router"
              config: {}
          route_config:
            virtual_hosts:
              - name: "blah"
                domains: "*"
                routes:
                  - match: { prefix: "/" }
                    route: { cluster: "my-service" }

